In [ ]:
import numpy as np

In [ ]:
A = np.array([[3, 2], [4, 1]])
print(A)

[[3 2]
 [4 1]]


In [ ]:
autovalores ,autovectores = np.linalg.eig(A)


In [ ]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [ ]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [ ]:
print(A_calc)

[[3. 2.]
 [4. 1.]]


In [ ]:
A = np.array([[3,2], [2,3]])
print(A)

[[3 2]
 [2 3]]


In [ ]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [ ]:
autovalores ,autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=648f5d22-7d8b-4325-a5ca-73f69fb5231f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>