In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2,3], [3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [ ]:
U, D, V = np.linalg.svd(A)

In [ ]:
print(U)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [ ]:
print(D)

[7.97638869 0.61418515]


In [ ]:
print(np.diag(D))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [ ]:
print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=648f5d22-7d8b-4325-a5ca-73f69fb5231f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>